### ISSUE TITLE
everquic no longer builds with latest everest

### ISSUE THREAD

**Issue by gebner** [project-everest/everquic-crypto#9]
Same issue as https://github.com/hacl-star/merkle-tree/issues/11.  I'm getting the following error when building everquic using the everest build scripts:
```
In file included from internal/EverQuic_EverCrypt.h:7,
                 from EverQuic_EverCrypt.c:3:
/home/gebner/everest/everquic-crypto/dist/internal/EverQuic_Krmllib.h:13:1: error: inline declaration of ‘FStar_UInt32_eq_mask’ follows declaration with attribute ‘noinline’ [-Werror=attributes]
   13 | static inline uint32_t FStar_UInt32_eq_mask(uint32_t a, uint32_t b);
      | ^~~~~~
```

An update of the `dist` directory (using `rm dist/Makefile.basic; make dist/Makefile.basic`) fixes the issue.  I can submit a PR updating that directory if you want.

**Comment by msprotz** [comment]
yes that'd be great, thanks!
